#!/bin/sh

first_line='# \$''Revision:.*\$, \$''Date:.*\$'
changelog_line='%changelog'
define_date_line='%define[\t ]*date[\t ]*.*'

x=$@
if [ "${x%.spec}" = "$x" ]; then
    cvs $@
else
    cvs $@ | \
        sed -e "
		/^${first_line}$/d
		/^${define_date_line}$/,\$d
	"  | \
        sed -e "
		# kill last empty line(s)
		\${/^\$/d}
        "
fi
